---
- hosts: all
  vars:
    host_uploads_directory: /srv/{{ app_name }}/uploads
  vars_files:
    - vars/app-common.yml
    - vars/app-secrets.yml
  tasks:
    - name: Get dokku homedir
      getent: database=passwd key=dokku split=':'
    - name: Set the dokku homedir fact
      set_fact:
        dokku_homedir={{ getent_passwd['dokku'][4] }}
    - name: Deploy dokku-ansible deploy key
      copy: src=dokku-ansible-deploy-key dest={{ dokku_homedir }}/.ssh/dokku-ansible-deploy-key mode=0600 owner=dokku group=dokku
    - name: Deploy dokku-ansible ssh config
      copy: src=dokku-ansible-ssh-config dest={{ dokku_homedir }}/.ssh/config mode=0644 owner=dokku group=dokku
    - name: Ensure github.com is a known host
      known_hosts:
        name: github.com
        key: "github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ=="
      become_user: dokku
    - name: Create {{ app_name }} dokku app
      dokku_apps:
        name: '{{ app_name }}'
      tags:
        - dokku.app
    - name: Create and link database for {{ app_name }}
      dokku_postgres:
        name: '{{ app_name }}'
        link: '{{ app_name }}'
        state: linked
      tags:
        - dokku.postgres
    - name: Setup uploads directory
      file:
        path: '{{ host_uploads_directory }}'
        state: directory
        owner: 32767
        group: 32767
        mode: 0755
        recurse: true
      tags:
        - dokku.storage
    - name: Setup storage mount
      dokku_storage:
        app: '{{ app_name }}'
        host: '{{ host_uploads_directory }}'
        guest: /app/uploads
      tags:
        - dokku.storage
    - name: Remove default domain
      dokku_domains:
        app: '{{ app_name }}'
        domain: '{{ app_name }}.{{ hostname }}'
        state: absent
      tags:
        - dokku.domains
    - name: Setup actual domain
      dokku_domains:
        app: '{{ app_name }}'
        domain: '{{ hostname }}'
      tags:
        - dokku.domains
    - name: Scale application
      dokku_ps:
        app: '{{ app_name }}'
        state: scaled
        scale:
          - web={{ apitp_web_workers }}
          - work=1
      tags:
        - dokku.scale
    - name: Set {{ app_name }} config
      dokku_config:
        app: '{{ app_name }}'
        config:
          - APITP_EMAIL={{ apitp_email }}
          - APITP_GPG_KEY={{ apitp_gpg_key }}
          - APITP_MAILGUN_KEY={{ apitp_mailgun_key }}
          - APITP_MAILGUN_DOMAIN={{ apitp_mailgun_domain }}
          - APITP_HOST={{ hostname }}
          - APITP_POSTMASTER={{ apitp_postmaster }}
          - APITP_MAX_UPLOAD_SIZE={{ apitp_max_upload_size_mb * 1024 * 1024 }}
          - APITP_SSL=1
          - DOKKU_LETSENCRYPT_EMAIL={{ apitp_email }}
          - RAILS_LOG_TO_STDOUT=1
          - RAILS_SERVE_STATIC_FILES=1
          - RAILS_ENV=production
          - SECRET_KEY_BASE={{ apitp_secret }}
      notify:
        - rebuild app
      tags:
        - dokku.config
    - name: Create nginx config extra dir
      file:
        path: '{{ dokku_homedir }}/{{ app_name }}/nginx.conf.d'
        state: directory
        owner: dokku
        group: dokku
        mode: 0755
      register: nginx_conf_d
    - name: Add nginx config for upload size
      copy:
        content: |
          client_max_body_size {{ apitp_max_upload_size_mb }}m;
        dest: '{{ nginx_conf_d.path }}/upload.conf'
        owner: dokku
        group: dokku
        mode: 0644
      notify:
        - reload nginx
    - name: Set APITP_TEAM_SUBMISSIONS
      dokku_config:
        app: '{{ app_name }}'
        config:
          - APITP_TEAM_SUBMISSIONS={{ apitp_team_submissions }}
      when: apitp_team_submissions == 1
      notify:
        - rebuild app
      tags:
        - dokku.config
  handlers:
    - name: "rebuild app"
      dokku_ps:
        # ps:rebuild is currently broken, so we ps:rebuildall instead
        #app: '{{ app_name }}'
        state: rebuilt
    - name: "reload nginx"
      systemd: name=nginx.service state=reloaded
