---
- name: Create swap file
  command: dd if=/dev/zero of={{ swap_file_path }} bs=1024 count={{ swap_file_size }}
           creates="{{ swap_file_path }}"
- name: Change swap permissions
  file: path="{{ swap_file_path }}"
        owner=root
        group=root
        mode=0600
- name: Check swap file type
  command: file {{ swap_file_path }}
  register: swapfile
- name: Make swap file
  command: mkswap {{ swap_file_path }}
  when: not ansible_check_mode and swapfile.stdout.find('swap file') == -1
- name: Write swap entry in fstab
  mount: name=none
         src={{ swap_file_path }}
         fstype=swap
         opts=sw
         passno=0
         dump=0
         state=present
- name: Mount swap
  command: swapon {{ swap_file_path }}
  when: ansible_swaptotal_mb < 1
- name: Set swappiness
  sysctl:
    name: vm.swappiness
    value: 1
